### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by sathwik2809** [sathwik2809/DSA-algorithms#5]

**Comment by Shivkant-Chauhan** [comment]
please assign this to me

**Comment by sathwik2809** [comment]
> please assign this to me

You can proceed

**Comment by Shivkant-Chauhan** [comment]
https://github.com/sathwik2809/DSA-algorithms/pull/6

**Comment by Shivkant-Chauhan** [comment]
@sathwik2809 please merge
